---
- name: Install Docker
  hosts: altair
  become: yes
  vars:
    DOCKER_COMPOSE_VERSION: "1.29.2"
    DOCKER_PACKAGES:
      - apt-transport-https
      - jq
      - docker.io
    USER: "talha"

  tasks:
    - name: Update apt packages
      apt:
        update_cache: "yes"
        force_apt_get: "yes"

    - name: Install packages needed for Docker
      apt:
        name: "{{ DOCKER_PACKAGES }}"
        state: present
        force_apt_get: "yes"

    - name: Save the current Ubuntu release version into a variable
      shell: lsb_release -cs
      register: ubuntu_version

    - name: Create docker group
      group:
        name: "docker"
        state: present

    - name: Adding user {{ USER }} to docker group
      user:
        name: "{{ USER }}"
        groups: "docker"
        append: "yes"

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/{{ DOCKER_COMPOSE_VERSION }}/docker-compose-Linux-x86_64
        dest: "/usr/local/bin/docker-compose"
        mode: 0755

    - name: get docker compose file for es-kibana
      shell: |
        mkdir -p /home/{{ USER }}/es-kibana
        wget https://raw.githubusercontent.com/Talha-Altair/es-kibana/master/docker-compose.yml -O /home/{{ USER }}/es-kibana/docker-compose.yml
    
    - name: Run docker compose
      shell: |
        cd /home/{{ USER }}/es-kibana
        docker-compose up -d
        echo "Docker compose up and running"
...

